name: Deploy React GitHub Actions

on:
    push:
        branches: ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Teste
              run: echo "Testando GitHub Actions"