name: Deploy React GitHub Actions

on:
    push:
        branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    deploy-react:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Iniciando o deploy
              run: echo "Iniciando o deploy"
              
            - name: Configurando o Node
              uses: actions/setup-node@v4
              with:
                node-version: 18
            
            - name: Instalação das dependências
              run: npm install
            
            - name: Build da aplicação
              run: npm run build

            - name: Listando pastas da máquina virtual
              run: ls

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                # Upload entire repository
                path: './production-build'

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4